/*
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package rmit.saintgiong.notificationservice.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ApplicantNotificationAction extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1058743327685376033L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicantNotificationAction\",\"namespace\":\"rmit.saintgiong.notificationservice.avro\",\"fields\":[{\"name\":\"companyId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"applicantId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<ApplicantNotificationAction> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ApplicantNotificationAction> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ApplicantNotificationAction> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ApplicantNotificationAction> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ApplicantNotificationAction> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ApplicantNotificationAction to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ApplicantNotificationAction from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ApplicantNotificationAction instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ApplicantNotificationAction fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.UUID companyId;
  private java.util.UUID applicantId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicantNotificationAction() {}

  /**
   * All-args constructor.
   * @param companyId The new value for companyId
   * @param applicantId The new value for applicantId
   */
  public ApplicantNotificationAction(java.util.UUID companyId, java.util.UUID applicantId) {
    this.companyId = companyId;
    this.applicantId = applicantId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return companyId;
    case 1: return applicantId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      new org.apache.avro.Conversions.UUIDConversion(),
      new org.apache.avro.Conversions.UUIDConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: companyId = (java.util.UUID)value$; break;
    case 1: applicantId = (java.util.UUID)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public java.util.UUID getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.util.UUID value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'applicantId' field.
   * @return The value of the 'applicantId' field.
   */
  public java.util.UUID getApplicantId() {
    return applicantId;
  }


  /**
   * Sets the value of the 'applicantId' field.
   * @param value the value to set.
   */
  public void setApplicantId(java.util.UUID value) {
    this.applicantId = value;
  }

  /**
   * Creates a new ApplicantNotificationAction RecordBuilder.
   * @return A new ApplicantNotificationAction RecordBuilder
   */
  public static rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder newBuilder() {
    return new rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder();
  }

  /**
   * Creates a new ApplicantNotificationAction RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicantNotificationAction RecordBuilder
   */
  public static rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder newBuilder(rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder other) {
    if (other == null) {
      return new rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder();
    } else {
      return new rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder(other);
    }
  }

  /**
   * Creates a new ApplicantNotificationAction RecordBuilder by copying an existing ApplicantNotificationAction instance.
   * @param other The existing instance to copy.
   * @return A new ApplicantNotificationAction RecordBuilder
   */
  public static rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder newBuilder(rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction other) {
    if (other == null) {
      return new rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder();
    } else {
      return new rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder(other);
    }
  }

  /**
   * RecordBuilder for ApplicantNotificationAction instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicantNotificationAction>
    implements org.apache.avro.data.RecordBuilder<ApplicantNotificationAction> {

    private java.util.UUID companyId;
    private java.util.UUID applicantId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.applicantId)) {
        this.applicantId = data().deepCopy(fields()[1].schema(), other.applicantId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicantNotificationAction instance
     * @param other The existing instance to copy.
     */
    private Builder(rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.companyId)) {
        this.companyId = data().deepCopy(fields()[0].schema(), other.companyId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.applicantId)) {
        this.applicantId = data().deepCopy(fields()[1].schema(), other.applicantId);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public java.util.UUID getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder setCompanyId(java.util.UUID value) {
      validate(fields()[0], value);
      this.companyId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'applicantId' field.
      * @return The value.
      */
    public java.util.UUID getApplicantId() {
      return applicantId;
    }


    /**
      * Sets the value of the 'applicantId' field.
      * @param value The value of 'applicantId'.
      * @return This builder.
      */
    public rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder setApplicantId(java.util.UUID value) {
      validate(fields()[1], value);
      this.applicantId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'applicantId' field has been set.
      * @return True if the 'applicantId' field has been set, false otherwise.
      */
    public boolean hasApplicantId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'applicantId' field.
      * @return This builder.
      */
    public rmit.saintgiong.notificationservice.avro.ApplicantNotificationAction.Builder clearApplicantId() {
      applicantId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ApplicantNotificationAction build() {
      try {
        ApplicantNotificationAction record = new ApplicantNotificationAction();
        record.companyId = fieldSetFlags()[0] ? this.companyId : (java.util.UUID) defaultValue(fields()[0]);
        record.applicantId = fieldSetFlags()[1] ? this.applicantId : (java.util.UUID) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ApplicantNotificationAction>
    WRITER$ = (org.apache.avro.io.DatumWriter<ApplicantNotificationAction>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ApplicantNotificationAction>
    READER$ = (org.apache.avro.io.DatumReader<ApplicantNotificationAction>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }


  @Override
  public int hashCode() {
    int result = 1;
    result = 31 * result + (companyId == null ? 0 : companyId.hashCode());
    result = 31 * result + (applicantId == null ? 0 : applicantId.hashCode());
    return result;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof ApplicantNotificationAction)) {
      return false;
    }
    ApplicantNotificationAction other = (ApplicantNotificationAction) o;
    if (!java.util.Objects.equals(this.companyId, other.companyId)) {
      return false;
    }
    if (!java.util.Objects.equals(this.applicantId, other.applicantId)) {
      return false;
    }
    return true;
  }
}










